---
title: "Homework 4"
author: "Mari Sanders"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(igraph)
data <- read_delim("moreno_oz/out.moreno_oz_oz", skip = 1) %>% select(1:3) 
```

# Making the Graph 

```{r}
edge_list <- data %>% select(1:2) %>% as.data.frame()
g <- graph_from_data_frame(edge_list)
E(g)$weight <- data %>% select(3) %>% pull()
summary(g)

igraph_options(vertex.size=5, vertex.label=NA, edge.arrow.size=0.5)
plot(g, layout = layout_with_kk)
```

# Degree 

```{r}
d.graph <- degree(g)
dd.graph <- degree_distribution(g)
d <- 1:max(d.graph) -1
ind <- (dd.graph !=0)
plot(d[ind],dd.graph[ind], col = "blue", xlab = c("Degree"), ylab = c("Frequency"), main = "Degree Distribution")
```

```{r}
In.degree <- degree(g, mode = c("in"))
out.degree <- degree(g, mode = "out")

comparingdegree <- cbind(d.graph, In.degree, out.degree)
comparingdegree %>% head()
```

# Eigenvector Centralilty 

```{r}
eig <- eigen_centrality(g)
eig$vector %>% head()
d <- 1:max(eig$value) - 1
ind <- (eig$value != 0)
plot(d[ind],eig$vector[ind], col = "blue", xlab = c("Degree"), ylab = c("Frequency"), main = "Degree Distribution")
```

# Hubs and Authorities 

```{r}
Hub <- hits_scores(g)
Hub$hub %>% head 
Hub$authority %>% head
```

# Closeness Centrality 

```{r}
closeness <- closeness(g)
closeness %>% head()
```

# Betweenness 

```{r}
Betweeness <- betweenness(g) 
Betweeness %>% head()
```

